# Generated by Django 4.0 on 2021-12-08 08:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='AGE',
            field=models.CharField(blank=True, choices=[('18_24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('64 AND OLDER', '64 AND OLDER')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='CHILDREN',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='GENDER',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='GOAL',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('I want to increase happiness', 'I want to increase happiness'), ('I want to express gratitude', 'I want to express gratitude'), ('I want an energy boost', 'I want an energy boost'), ('I want to feel more confident', 'I want to feel more confident'), ('I wanat to feel peace', 'I wanat to feel peace')], max_length=131, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='RELATIONSHIP',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=30, null=True),
        ),
    ]
