# Generated by Django 4.0 on 2021-12-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_user_age_alter_user_children_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NAME',
            field=models.CharField(default='exit', max_length=30),
            preserve_default=False,
        ),
    ]
