# Generated by Django 4.0 on 2021-12-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_activity_dailyquote_smile_goal_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('resource', models.CharField(choices=[('COMMUNITY', 'COMMUNITY'), ('SMILE SCIENCE', 'SMILE SCIENCE'), ('LEVEL', 'LEVEL'), ('NOTIFICATION', 'NOTIFICATION')], max_length=30)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Smilescience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
            ],
        ),
    ]
