# Generated by Django 3.2.9 on 2021-12-07 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
