# Generated by Django 4.0.2 on 2022-02-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('idCard', models.IntegerField()),
                ('roll', models.IntegerField()),
            ],
        ),
    ]
